spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin#60
    url: jdbc:mysql://172.16.20.169:3306/edsip-mirror?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

  thymeleaf:
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    # 模板的模式
    mode: HTML5

edsip:
  lifesmart:
    app:
      appkey: ja9ekycTGDt5GiyozHc68g
      apptoken: GHWobCwPhBqmdMa6eN9hnA




